channels:
  - conda-forge

dependencies:
  - python=3.8
  # https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/
  - c-compiler=1.3.0
  - cmake=3.21.3
  - qt=5.12.5  # conda-forge does not have 5.13.2 available
  - pip
  - pip:
    - gym3==0.3.3
    - numpy>=1.21
    - gym==0.15.3
    - filelock==3.0.10
    - git+https://github.com/jordan-schneider/linear-procgen.git
